In [1]:
import pickle
import numpy as np


In [3]:
ohe_sex = pickle.load(open('./model/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('./model/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('./model/model.pkl', 'rb'))




In [4]:
# assume the user input

test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [5]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [ ]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_embarked = ohe_embarked.transform(test_input[:,6].reshape(1,1))


c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [9]:
test_input_age = test_input[:, 2].reshape(1, 1)

In [14]:
test_input_transformed = np.concatenate((  test_input[:, [0,3,4,5]]  ,test_input_age, test_input_sex, test_input_embarked), axis=1)

In [15]:
test_input_transformed.shape

(1, 11)

In [16]:
# prediction 

clf.predict(test_input_transformed)

array([1])