In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np

# Correct 2D array: 5 samples, 1 feature each
sizes = np.array([["Small"], ["Medium"], ["Large"], ["Xtra Large"], ["XXtra Large"]])

# Label Encoding (needs 1D)
label_encoder = LabelEncoder()
encoded_sizes = label_encoder.fit_transform(sizes.flatten())  # flatten 2D -> 1D

# One-Hot Encoding (NEW sklearn)
onehot_encoder = OneHotEncoder(sparse_output=False)
encoded_sizes_2 = onehot_encoder.fit_transform(sizes)

# Print outputs
print("Label Encoded:", encoded_sizes)
print("One-Hot Encoded:\n", encoded_sizes_2)

# Print features / vocabulary
print("Features:", onehot_encoder.get_feature_names_out())



# always make a vector the categorical variable and store in aphabetical order
# from sklearn.preprocessing import OneHotEncoder
# import numpy as np

# fruits = np.array([["Banana"], ["Apple"], ["Cherry"], ["Banana"], ["Apple"],["Dargon_Fruit"]])

# # One-Hot Encoding
# onehot_encoder = OneHotEncoder(sparse_output=False)
# encoded_fruits = onehot_encoder.fit_transform(fruits)

# # Feature names
# feature_names = onehot_encoder.get_feature_names_out()

# print("Original Fruits:", fruits.flatten())
# print("One-Hot Encoded:\n", encoded_fruits)
# print("Column Index → Category Mapping:")
# for i, name in enumerate(feature_names):
#     print(f"Column {i} → {name}")




Label Encoded: [2 1 0 4 3]
One-Hot Encoded:
 [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
Features: ['x0_Large' 'x0_Medium' 'x0_Small' 'x0_XXtra Large' 'x0_Xtra Large']
['Large' 'Medium' 'Small' 'XXtra Large' 'Xtra Large']
